// Generated by gencpp from file precise_pushing_bridge/StepResponse.msg
// DO NOT EDIT!


#ifndef PRECISE_PUSHING_BRIDGE_MESSAGE_STEPRESPONSE_H
#define PRECISE_PUSHING_BRIDGE_MESSAGE_STEPRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace precise_pushing_bridge
{
template <class ContainerAllocator>
struct StepResponse_
{
  typedef StepResponse_<ContainerAllocator> Type;

  StepResponse_()
    : reward(0.0)
    , done(false)  {
    }
  StepResponse_(const ContainerAllocator& _alloc)
    : reward(0.0)
    , done(false)  {
  (void)_alloc;
    }



   typedef float _reward_type;
  _reward_type reward;

   typedef uint8_t _done_type;
  _done_type done;





  typedef boost::shared_ptr< ::precise_pushing_bridge::StepResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::precise_pushing_bridge::StepResponse_<ContainerAllocator> const> ConstPtr;

}; // struct StepResponse_

typedef ::precise_pushing_bridge::StepResponse_<std::allocator<void> > StepResponse;

typedef boost::shared_ptr< ::precise_pushing_bridge::StepResponse > StepResponsePtr;
typedef boost::shared_ptr< ::precise_pushing_bridge::StepResponse const> StepResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::precise_pushing_bridge::StepResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::precise_pushing_bridge::StepResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::precise_pushing_bridge::StepResponse_<ContainerAllocator1> & lhs, const ::precise_pushing_bridge::StepResponse_<ContainerAllocator2> & rhs)
{
  return lhs.reward == rhs.reward &&
    lhs.done == rhs.done;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::precise_pushing_bridge::StepResponse_<ContainerAllocator1> & lhs, const ::precise_pushing_bridge::StepResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace precise_pushing_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::precise_pushing_bridge::StepResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::precise_pushing_bridge::StepResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::precise_pushing_bridge::StepResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::precise_pushing_bridge::StepResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::precise_pushing_bridge::StepResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::precise_pushing_bridge::StepResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::precise_pushing_bridge::StepResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a28b027ac30cbc047f58b69ea622b8a";
  }

  static const char* value(const ::precise_pushing_bridge::StepResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a28b027ac30cbc0ULL;
  static const uint64_t static_value2 = 0x47f58b69ea622b8aULL;
};

template<class ContainerAllocator>
struct DataType< ::precise_pushing_bridge::StepResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "precise_pushing_bridge/StepResponse";
  }

  static const char* value(const ::precise_pushing_bridge::StepResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::precise_pushing_bridge::StepResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Response\n"
"float32 reward\n"
"bool done\n"
"\n"
;
  }

  static const char* value(const ::precise_pushing_bridge::StepResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::precise_pushing_bridge::StepResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.reward);
      stream.next(m.done);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StepResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::precise_pushing_bridge::StepResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::precise_pushing_bridge::StepResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "reward: ";
    Printer<float>::stream(s, indent + "  ", v.reward);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "done: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.done);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRECISE_PUSHING_BRIDGE_MESSAGE_STEPRESPONSE_H
