// Generated by gencpp from file precise_pushing_bridge/StepRequest.msg
// DO NOT EDIT!


#ifndef PRECISE_PUSHING_BRIDGE_MESSAGE_STEPREQUEST_H
#define PRECISE_PUSHING_BRIDGE_MESSAGE_STEPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace precise_pushing_bridge
{
template <class ContainerAllocator>
struct StepRequest_
{
  typedef StepRequest_<ContainerAllocator> Type;

  StepRequest_()
    : action()  {
    }
  StepRequest_(const ContainerAllocator& _alloc)
    : action(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _action_type;
  _action_type action;





  typedef boost::shared_ptr< ::precise_pushing_bridge::StepRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::precise_pushing_bridge::StepRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StepRequest_

typedef ::precise_pushing_bridge::StepRequest_<std::allocator<void> > StepRequest;

typedef boost::shared_ptr< ::precise_pushing_bridge::StepRequest > StepRequestPtr;
typedef boost::shared_ptr< ::precise_pushing_bridge::StepRequest const> StepRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::precise_pushing_bridge::StepRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::precise_pushing_bridge::StepRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::precise_pushing_bridge::StepRequest_<ContainerAllocator1> & lhs, const ::precise_pushing_bridge::StepRequest_<ContainerAllocator2> & rhs)
{
  return lhs.action == rhs.action;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::precise_pushing_bridge::StepRequest_<ContainerAllocator1> & lhs, const ::precise_pushing_bridge::StepRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace precise_pushing_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::precise_pushing_bridge::StepRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::precise_pushing_bridge::StepRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::precise_pushing_bridge::StepRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::precise_pushing_bridge::StepRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::precise_pushing_bridge::StepRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::precise_pushing_bridge::StepRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::precise_pushing_bridge::StepRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a70a7d92e0376dcb967914076f276ea6";
  }

  static const char* value(const ::precise_pushing_bridge::StepRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa70a7d92e0376dcbULL;
  static const uint64_t static_value2 = 0x967914076f276ea6ULL;
};

template<class ContainerAllocator>
struct DataType< ::precise_pushing_bridge::StepRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "precise_pushing_bridge/StepRequest";
  }

  static const char* value(const ::precise_pushing_bridge::StepRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::precise_pushing_bridge::StepRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request: action vector (shape must match your env's action_space)\n"
"float32[] action\n"
;
  }

  static const char* value(const ::precise_pushing_bridge::StepRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::precise_pushing_bridge::StepRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StepRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::precise_pushing_bridge::StepRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::precise_pushing_bridge::StepRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "action: ";
    if (v.action.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.action.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.action[i]);
    }
    if (v.action.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRECISE_PUSHING_BRIDGE_MESSAGE_STEPREQUEST_H
