// Generated by gencpp from file precise_pushing_bridge/Step.msg
// DO NOT EDIT!


#ifndef PRECISE_PUSHING_BRIDGE_MESSAGE_STEP_H
#define PRECISE_PUSHING_BRIDGE_MESSAGE_STEP_H

#include <ros/service_traits.h>


#include <precise_pushing_bridge/StepRequest.h>
#include <precise_pushing_bridge/StepResponse.h>


namespace precise_pushing_bridge
{

struct Step
{

typedef StepRequest Request;
typedef StepResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Step
} // namespace precise_pushing_bridge


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::precise_pushing_bridge::Step > {
  static const char* value()
  {
    return "8cc3aa28258e546257d5cfcc54ad965b";
  }

  static const char* value(const ::precise_pushing_bridge::Step&) { return value(); }
};

template<>
struct DataType< ::precise_pushing_bridge::Step > {
  static const char* value()
  {
    return "precise_pushing_bridge/Step";
  }

  static const char* value(const ::precise_pushing_bridge::Step&) { return value(); }
};


// service_traits::MD5Sum< ::precise_pushing_bridge::StepRequest> should match
// service_traits::MD5Sum< ::precise_pushing_bridge::Step >
template<>
struct MD5Sum< ::precise_pushing_bridge::StepRequest>
{
  static const char* value()
  {
    return MD5Sum< ::precise_pushing_bridge::Step >::value();
  }
  static const char* value(const ::precise_pushing_bridge::StepRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::precise_pushing_bridge::StepRequest> should match
// service_traits::DataType< ::precise_pushing_bridge::Step >
template<>
struct DataType< ::precise_pushing_bridge::StepRequest>
{
  static const char* value()
  {
    return DataType< ::precise_pushing_bridge::Step >::value();
  }
  static const char* value(const ::precise_pushing_bridge::StepRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::precise_pushing_bridge::StepResponse> should match
// service_traits::MD5Sum< ::precise_pushing_bridge::Step >
template<>
struct MD5Sum< ::precise_pushing_bridge::StepResponse>
{
  static const char* value()
  {
    return MD5Sum< ::precise_pushing_bridge::Step >::value();
  }
  static const char* value(const ::precise_pushing_bridge::StepResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::precise_pushing_bridge::StepResponse> should match
// service_traits::DataType< ::precise_pushing_bridge::Step >
template<>
struct DataType< ::precise_pushing_bridge::StepResponse>
{
  static const char* value()
  {
    return DataType< ::precise_pushing_bridge::Step >::value();
  }
  static const char* value(const ::precise_pushing_bridge::StepResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PRECISE_PUSHING_BRIDGE_MESSAGE_STEP_H
